version: "3.8"
services:
  db:
    container_name: PostGis
    image: "postgis/postgis:latest"
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: geolocalizacao
    ports:
      - "5433:5432"
    volumes:
      - "./postgres_data:/var/lib/postgresql/data"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
